{"uuid": "c39ec15d-fad8-428d-9434-7c382b30fb79", "children": ["0eb8105c-101e-4f22-948b-4c0bd6ecd6b4"], "befores": [{"name": "setup_alerts_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=140.0.7339.208)\nStacktrace:\n0   chromedriver                        0x000000010f295f08 chromedriver + 5934856\n1   chromedriver                        0x000000010f28dc9a chromedriver + 5901466\n2   chromedriver                        0x000000010ed59ade chromedriver + 445150\n3   chromedriver                        0x000000010ed2cca0 chromedriver + 261280\n4   chromedriver                        0x000000010eddfc65 chromedriver + 994405\n5   chromedriver                        0x000000010edfca9b chromedriver + 1112731\n6   chromedriver                        0x000000010edd7503 chromedriver + 959747\n7   chromedriver                        0x000000010eda0731 chromedriver + 735025\n8   chromedriver                        0x000000010eda1ee1 chromedriver + 741089\n9   chromedriver                        0x000000010f25f360 chromedriver + 5710688\n10  chromedriver                        0x000000010f261c00 chromedriver + 5721088\n11  chromedriver                        0x000000010f26177b chromedriver + 5719931\n12  chromedriver                        0x000000010f2620a5 chromedriver + 5722277\n13  chromedriver                        0x000000010f244e97 chromedriver + 5602967\n14  chromedriver                        0x000000010f262372 chromedriver + 5722994\n15  chromedriver                        0x000000010f238584 chromedriver + 5551492\n16  chromedriver                        0x000000010f27dd28 chromedriver + 5836072\n17  chromedriver                        0x000000010f27de85 chromedriver + 5836421\n18  chromedriver                        0x000000010f28d823 chromedriver + 5900323\n19  libsystem_pthread.dylib             0x00007ff81aad4e59 _pthread_start + 115\n20  libsystem_pthread.dylib             0x00007ff81aad0857 thread_start + 15\n\n", "trace": "  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/pvon/Documents/estagio-automation/tests/test_alert.py\", line 9, in setup_alerts_page\n    home_page.click_alert_frame_windows_card()\n  File \"/Users/pvon/Documents/estagio-automation/pages/alert_pages.py\", line 18, in click_alert_frame_windows_card\n    element = self.driver.find_element(*self.alerts_frames_windows_card)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 926, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1759156486895, "stop": 1759156487126}], "start": 1759156486895, "stop": 1759156487168}