{"uuid": "33c7604e-b493-4f9d-ad95-2af4b7b2ebee", "children": ["6cd6fa3a-5707-450b-8f51-46f84e72cb47"], "befores": [{"name": "setup_alerts_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=140.0.7339.208)\nStacktrace:\n0   chromedriver                        0x0000000105946f08 chromedriver + 5934856\n1   chromedriver                        0x000000010593ec9a chromedriver + 5901466\n2   chromedriver                        0x000000010540aade chromedriver + 445150\n3   chromedriver                        0x00000001053ddca0 chromedriver + 261280\n4   chromedriver                        0x0000000105490c65 chromedriver + 994405\n5   chromedriver                        0x00000001054ada9b chromedriver + 1112731\n6   chromedriver                        0x0000000105488503 chromedriver + 959747\n7   chromedriver                        0x0000000105451731 chromedriver + 735025\n8   chromedriver                        0x0000000105452ee1 chromedriver + 741089\n9   chromedriver                        0x0000000105910360 chromedriver + 5710688\n10  chromedriver                        0x0000000105912c00 chromedriver + 5721088\n11  chromedriver                        0x000000010591277b chromedriver + 5719931\n12  chromedriver                        0x00000001059130a5 chromedriver + 5722277\n13  chromedriver                        0x00000001058f5e97 chromedriver + 5602967\n14  chromedriver                        0x0000000105913372 chromedriver + 5722994\n15  chromedriver                        0x00000001058e9584 chromedriver + 5551492\n16  chromedriver                        0x000000010592ed28 chromedriver + 5836072\n17  chromedriver                        0x000000010592ee85 chromedriver + 5836421\n18  chromedriver                        0x000000010593e823 chromedriver + 5900323\n19  libsystem_pthread.dylib             0x00007ff81aad4e59 _pthread_start + 115\n20  libsystem_pthread.dylib             0x00007ff81aad0857 thread_start + 15\n\n", "trace": "  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/_pytest/fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/pvon/Documents/estagio-automation/tests/test_alert.py\", line 9, in setup_alerts_page\n    home_page.click_alert_frame_windows_card()\n  File \"/Users/pvon/Documents/estagio-automation/pages/alert_pages.py\", line 17, in click_alert_frame_windows_card\n    self.driver.find_element(*self.alerts_frames_windows_card).click()\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 926, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/pvon/Documents/estagio-automation/myproject/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1759155947220, "stop": 1759155948188}], "start": 1759155947220, "stop": 1759155948234}